name=pid-autotune
version=1.1.0
author=ahmedosama07
maintainer=ahmedosama07
sentence=PID autotuning library
paragraph=Automatically tunes PID control loops using the Ziegler-Nichols method. Includes high-resolution timing and angular support.
category=Device Control
url=https://github.com/ahmedosama07/PID-autotune
architectures=*
